package cn.virtuepay;

import org.junit.BeforeClass;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Afon' at '16-12-16 上午10:33' with Gradle 3.1
 *
 * @author Afon, @date 16-12-16 上午10:33
 */
public class XPayTestBase {

    @BeforeClass public static void initApiKey() {
        VirtuePay.overrideApiBase(XPayTestData.getApiBase());
        VirtuePay.apiKey = XPayTestData.getApiKey();
        VirtuePay.appId = XPayTestData.getAppID();
        VirtuePay.privateKey = XPayTestData.getPKCS8PrivateKey();

        VirtuePay.DEBUG = true;
    }
}
